<?php
// +----------------------------------------------------------------------
// | Yesow 网站公共语言文件
// +-----------------------------------------------------------------------
// | Last Update Time : 2012-11-19 21:45
// +----------------------------------------------------------------------

if (!defined('THINK_PATH')) exit();
return array(
  'LOGIN_NAME_EMPTY' => '帐号不能为空,请重新输入',
  'NAME_ERROR' => '帐号不存在或已禁用,请重新输入',
  'LOGIN_PWD_EMPTY' => '密码不能为空,请重新输入',
  'PASSWORD_ERROR' => '登录密码错误,请重新输入',
  'MAIL_CHECK_ERROR' => '登录成功，您还没有通过邮箱验证，请先进行邮箱验证',
  'LOGIN_VERIFY_EMPTY' => '验证码不能为空',
  'VERIFY_ERROR' => '验证码错误',
  'LOGIN_SUCCESS' => '登录成功,欢迎光临',
  'LOGOUT_SUCCESS' => '退出成功',
  'LOGOUT_ERROR' => '退出失败，您已经退出',
  'LOGIN_NOT' => '您还未登录',
  'OLDPASSWORD_EMPTY' => '旧密码不能为空',
  'NEWPASSWORD_EMPTY' => '新密码不能为空',
  'REPASSWORD_EMPTY' => '重复新密码不能为空',
  'PASSWORD_NEQ' => '两次输入的密码不一致',
  'OLDPASSWORD_ERROR' => '原密码输入错误',
  'CHANGE_PWD_SUCCESS' => '更改密码成功',
  'CHANGE_PWD_ERROR' => '更改密码失败',
  'EMAIL_ERROR' => '电子邮件格式不符',
  'NAME_EMPTY_ERROR' => '名称不能为空',
  'NAME_UNIQUE_ERROR' => '名称不能重复',
  'DATA_UPDATE_SUCCESS' => '数据更新成功',
  'DATA_UPDATE_ERROR' => '数据更新失败',
  'DATA_ADD_SUCCESS' => '数据添加成功',
  'DATA_ADD_ERROR' => '数据添加失败',
  'DATA_DELETE_SUCCESS' => '数据删除成功',
  'DATA_DELETE_ERROR' => '数据删除失败',
  'STATUS_ERROR' => '状态码错误',
  'MONEY_ERROR' => '金额格式错误',
  'ARTICLE_CLASSID_EMPTY' => '所属分类不能为空',
  'ARTICLE_COLID_EMPTY' => '所属栏目不能为空',
  'ARTICLE_TID_EMPTY' => '标题属性不能为空',
  'ARTICLE_CONID_EMPTY' => '内容属性不能为空',
  'ARTICLE_TITLE_EMPTY' => '标题不能为空',
  'ARTICLE_CONTENT_EMPTY' => '内容不能为空',
  'ARTICLE_SOURCE_EMPTY' => '文章来源不能为空',
  'ARTICLE_KEYWORD_EMPTY' => '关键词不能为空',
  'MEMBER_NAME_EMPTY' => '会员用户名不能为空',
  'MEMBER_NAME_UNIQUE' => '会员用户名不能重复',
  'MEMBER_PWDQUESTION_EMPTY' => '会员密码提示问题不能为空',
  'MEMBER_PWDANSWER_EMPTY' => '会员密码提示答案不能为空',
  'MEMBER_NICKNAME_EMPTY' => '会员昵称不能为空',
  'MEMBER_PWD_EMPTY' => '会员登录密码不能为空',
  'MEMBER_TEL_EMPTY' => '会员联系电话不能为空',
  'MEMBER_EMAIL_EMPTY' => '会员电子邮件不能为空',
  'MEMBER_EMAIL_ERROR' => '会员电子邮件格式错误',
  'SEND_EMAIL_SUCCESS' => '验证邮件发送成功，请登录邮箱查收',
  'PASSWORD_EMAIL_SUCCESS' => '重置密码邮件发送成功，请登录邮箱查收',
  'CHECK_EMAIL_SUCCESS' => '邮箱验证成功，现在转到登录页面',
  'CHECK_EMAIL_ERROR' => '邮箱验证失败，请重新验证',
  'UPDETA_USER_DATA_CHENGE_EMAIL' => '数据更新成功，由于您更改了电子邮箱，所以需要再次验证',

);
